spring.application.name=urlshortener
server.port=8100

# MongoDB related configurations; Spring boot 4.x changes
spring.mongodb.uri=mongodb://localhost:27017/url_shortener?serverSelectionTimeoutMS=10000&connectTimeoutMS=10000&socketTimeoutMS=10000
spring.mongodb.database=url_shortener

# Logging
logging.level.com.projects.system.urlshortener=DEBUG

# Redis configurations
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.data.redis.timeout=5000ms
spring.data.redis.connect-timeout=10000ms
